### ISSUE TITLE
Doesn't work on HTML templates

### ISSUE THREAD

**Issue by codeshard** [MauricioDinki/django-atom#1]
Hi there! Awesome work! But doesn't work on my html templates, no syntax highlighting and no code snippets. I've no idea.
I'm using Atom v1.0 on Fedora 21 x86_64 and KDE 4.14.

**Comment by MauricioDinki** [comment]
Do you see this when you select your syntax ?
![seleccion](https://cloud.githubusercontent.com/assets/8716011/8702336/dedf5828-2adc-11e5-8999-0678ef1a06b9.jpg)

**Comment by codeshard** [comment]
Excuse the delay. Apparently it was a conflict with another package. Thank you very much for answering. You can close the issue. Thank you very much!
