### ISSUE TITLE
Syntax Highlighting and Autocomplete

### ISSUE THREAD

**Issue by pingshunhuangalex** [MauricioDinki/django-atom#4]
I just started using Atom and django-atom. After the installation, syntax colour kicks in which is good. However, I noticed if there is no space after `=` in attribute, the colour is not right.
![image](https://cloud.githubusercontent.com/assets/17170199/18937588/f3d4970c-8634-11e6-8de2-dd275d246a68.png)

Also, it seems the autocomplete is not working properly... None of the snippets are suggested when I type.
![image](https://cloud.githubusercontent.com/assets/17170199/18937611/2832dca2-8635-11e6-8935-47e53ae9b672.png)

Hope it can be fixed soon. Please keep up the good work!

**Comment by hlrossato** [comment]
I'm experiencing the same problem here!

**Comment by pingshunhuangalex** [comment]
I think the project is no longer active now, I'm just gonna close this issue.
